### PR TITLE
add default shopware cdn strategy in .env

### PR DESCRIPTION
**Pull request by zaifastafa**

### CODE REVIEW

**Comment by shyim** [comment]
why is this needed?

**Comment by zaifastafa** [comment]
> why is this needed?

I have seen several shops that we clone for local development has this CDN strategy in their .env file but our setup does not create this variable when setting up a shop, so thought it'd be good for consistency.

**Comment by shyim** [comment]
The argument works also in other way 😅 

Maybe define in that projects this explict in the config/services.xml

**Comment by zaifastafa** [comment]
So this is not needed in your opinion? Without this variable, the media images show broken in the shop if we have done a clone.

**Comment by zaifastafa** [comment]
I have verified it that when I remove this variable, the media images are broken. But when I add it, it is able to identify the path of the images correctly.

**Comment by shyim** [comment]
I guess the production system have a configuration like this in the config/packages https://github.com/shopware/production/blob/6.4/config/services/defaults.xml#L19-L20

**Comment by zaifastafa** [comment]
Here it defaults to `physical_filename`, but I saw in a commit I think that it was defaulting to `id` in the yaml file, so I suppose we can use the default cdn strategy to be `id` here too? That is easier to maintain I think then changing the yaml file for local setups.

**Pull request merged**
